/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package d.Vista;

import b.Entidades.Horario;
import b.Entidades.Ruta;
import c.Data.HorariosData;
import c.Data.RutaData;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FormularioHorarios extends javax.swing.JInternalFrame {

    RutaData rutaData;
    HorariosData horaData;
    /**
     * Creates new form GestionHorarios
     */
    public FormularioHorarios(RutaData rutaData, HorariosData horaData) {
        initComponents();
        this.rutaData = rutaData;
        this.horaData = horaData;
    }

    private void limpiar(){
            jTIDhorario.setText("");
            jTRutaAsignada.setText("");
            jCmodificarRuta.setSelectedIndex(-1);
            txtHoraSalida.setText("");
            txtHoraLlegada.setText("");          
            Estado1.setSelected(false);
    }
    
    private void setrutEnabled(boolean flag) {
        jTRutaAsignada.setEnabled(flag);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Estado1 = new javax.swing.JCheckBox();
        GuardarBTN = new javax.swing.JButton();
        LimpiarBTN = new javax.swing.JButton();
        SalirBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtHoraLlegada = new javax.swing.JTextField();
        BuscarBTN = new javax.swing.JButton();
        jCmodificarRuta = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTIDhorario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTRutaAsignada = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTextPane1);

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FormularioHorarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText(" Horarios");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel2.setText("Horario Salida:");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel3.setText("Horario Llegada:");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel4.setText("Estado:");

        Estado1.setText("jCheckBox1");

        GuardarBTN.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        GuardarBTN.setText("Registrar");
        GuardarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBTNActionPerformed(evt);
            }
        });

        LimpiarBTN.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        LimpiarBTN.setText("Limpiar");
        LimpiarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBTNActionPerformed(evt);
            }
        });

        SalirBTN.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        SalirBTN.setText("Salir");
        SalirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel5.setText("Modificar Ruta:");

        BuscarBTN.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        BuscarBTN.setText("Buscar");
        BuscarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo Horario:");

        jTIDhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDhorarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Ruta asignada:");

        jTRutaAsignada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRutaAsignadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LimpiarBTN)
                            .addGap(18, 18, 18)
                            .addComponent(GuardarBTN)
                            .addGap(409, 409, 409)
                            .addComponent(SalirBTN))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(txtHoraSalida))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(116, 116, 116)
                                    .addComponent(Estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHoraLlegada))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTIDhorario, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BuscarBTN))
                                    .addComponent(jTRutaAsignada)
                                    .addComponent(jCmodificarRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTIDhorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTRutaAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCmodificarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Estado1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimpiarBTN)
                    .addComponent(GuardarBTN)
                    .addComponent(SalirBTN))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimpiarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBTNActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_LimpiarBTNActionPerformed

    private void GuardarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBTNActionPerformed
        // TODO add your handling code here:
        String Id_horario = jTIDhorario.getText();
        String rutaAsignar =jCmodificarRuta.getSelectedItem().toString();
        String horaLlegada = txtHoraLlegada.getText();
        String horaSalida = txtHoraSalida.getText();
        boolean estado = Estado1.isSelected();
       System.out.println(estado);
       
       if(Id_horario.isBlank() || rutaAsignar.isBlank() || horaLlegada.isBlank() || horaSalida.isBlank()){           
           JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos" );
           return;
       }
       
       int id_hora = Integer.parseInt(Id_horario);
       Horario hora = horaData.buscarHorario(id_hora);
       Ruta rutas = (Ruta) jCmodificarRuta.getSelectedItem();
       LocalTime hora_Salida = LocalTime.parse(txtHoraSalida.getText()) ;
       LocalTime hora_Llegada = LocalTime.parse(txtHoraLlegada.getText()) ;
       boolean resultado;
       if(hora == null){
           hora = new Horario(id_hora,rutas,hora_Salida,hora_Llegada,estado);
           horaData.añadirHorario(hora);           
           resultado=true;
       }else{
           hora.setID_Horario(id_hora);
           hora.setRuta(rutas);
           hora.setHora_Llegada(hora_Llegada);
           hora.setHora_Salida(hora_Salida);
           hora.setEstado(estado);
           horaData.modificarHorario(hora);
           resultado=true;
       }
       
       //imprimir resultado
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Horario guardado o modificado");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo guardar el horario");
        }
    }//GEN-LAST:event_GuardarBTNActionPerformed

    private void SalirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBTNActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_SalirBTNActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        jCmodificarRuta.removeAllItems();
        List<Ruta> rutas = rutaData.listarRutas();
        for (Ruta rut : rutas) {
            jCmodificarRuta.addItem(rut);
        }
        jCmodificarRuta.setSelectedIndex(-1);
    }//GEN-LAST:event_formInternalFrameActivated

    private void BuscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBTNActionPerformed
        // TODO add your handling code here:
        //Validar ID_Horario
        setrutEnabled(false);
        int horario;        
        horario = Integer.parseInt(jTIDhorario.getText());                                      
        Horario hora = horaData.buscarHorario(horario);
        if(hora == null){
            limpiar();
            JOptionPane.showMessageDialog(null, "Horario no encontrado" );
        }else{
            jTIDhorario.setText(Integer.toString(hora.getID_Horario()));
            jTRutaAsignada.setText(hora.getRuta().toString());
            jCmodificarRuta.setSelectedItem(hora.getRuta());//no selecciona el combobox
            txtHoraLlegada.setText(hora.getHora_Llegada().toString());
            txtHoraSalida.setText(hora.getHora_Salida().toString());
            Estado1.setSelected(hora.isEstado());   
            setrutEnabled(false);
        }

    }//GEN-LAST:event_BuscarBTNActionPerformed

    private void jTIDhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDhorarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTIDhorarioActionPerformed

    private void jTRutaAsignadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRutaAsignadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRutaAsignadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBTN;
    private javax.swing.JCheckBox Estado1;
    private javax.swing.JButton GuardarBTN;
    private javax.swing.JButton LimpiarBTN;
    private javax.swing.JButton SalirBTN;
    private javax.swing.JComboBox<Ruta> jCmodificarRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTIDhorario;
    private javax.swing.JTextField jTRutaAsignada;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtHoraLlegada;
    private javax.swing.JTextField txtHoraSalida;
    // End of variables declaration//GEN-END:variables
}
