package d.Vista;

import b.Entidades.Pasajero;
import c.Data.PasajerosData;
import javax.swing.JOptionPane;

public class FormularioPasajeros extends javax.swing.JInternalFrame {

    PasajerosData pasajeroData;

    public FormularioPasajeros(PasajerosData pasajeroData) {
        initComponents();
        this.pasajeroData = pasajeroData;
    }

    private void limpiar() {
        textDNI.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        Estado1.setSelected(false);
    }
    //Metodos de validacion
    public static boolean esDNIValido(String dni) {
        if (dni == null || dni.length() > 8) {
            return false;
        }
        String regex = "\\d{1,8}";
        return dni.matches(regex);
    }
    public static boolean soloLetraNombre(String nombre) {
        if (nombre == null || nombre.length() > 15) {
            return false;
        }
        String regex = "^^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+( [a-zA-ZáéíóúÁÉÍÓÚñÑ]+)*$";
        return nombre.matches(regex);
    }
    
    public static boolean soloLetraApellido(String apellido) {
        if (apellido == null || apellido.length() > 30) {
            return false;
        }
        String regex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+( [a-zA-ZáéíóúÁÉÍÓÚñÑ]+)*$";
        return apellido.matches(regex);
    }
    
    public static boolean esNumeroValido(String telefono) {
        if (telefono == null || telefono.length() > 30) {
            return false;
        }
        String regex = "\\d{1,10}";
        return telefono.matches(regex);
    }
    public static boolean VerificacionMail(String correo) {
        if (correo == null) {
            return false;
        }
        
        String regex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}$";//aknsdikas@gmail.com
        return correo.matches(regex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Estado = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        textDNI = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Estado1 = new javax.swing.JCheckBox();
        Buscarbtn = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        DNI = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Limpiarbtn = new javax.swing.JButton();
        Registrarbtn = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulario pasajeros");

        Titulo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Titulo.setText("Formulario Pasajeros");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Estado.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Estado.setText("Estado :");

        Telefono.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Telefono.setText("Telefono:");

        Correo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Correo.setText("Correo:");

        Buscarbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Buscarbtn.setText("Comprobar");
        Buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarbtnActionPerformed(evt);
            }
        });

        DNI.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        DNI.setText("DNI:");

        Apellido.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Apellido.setText("Apellido :");

        Nombre.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Nombre.setText("Nombre :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Correo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Estado)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Estado1)
                                    .addComponent(txtCorreo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Telefono)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nombre)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Apellido)
                                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Buscarbtn)))))
                        .addGap(11, 11, 11))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(textDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscarbtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Estado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Estado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        Limpiarbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Limpiarbtn.setText("Limpiar");
        Limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarbtnActionPerformed(evt);
            }
        });

        Registrarbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Registrarbtn.setText("Registrar");
        Registrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarbtnActionPerformed(evt);
            }
        });

        Salirbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Salirbtn.setText("Salir");
        Salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Limpiarbtn)
                        .addGap(18, 18, 18)
                        .addComponent(Registrarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limpiarbtn)
                    .addComponent(Registrarbtn)
                    .addComponent(Salirbtn))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarbtnActionPerformed
        // TODO add your handling code here:

        //Validar DNI
        String dni;
        dni = textDNI.getText();
        if (esDNIValido(dni)==false) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI correcto.", "Error", JOptionPane.ERROR_MESSAGE);
            textDNI.setText("");
            return;
        }
        if(dni.isBlank()){           
           JOptionPane.showMessageDialog(this, "Por favor ingrese un Dni.", "Comprobar", JOptionPane.ERROR_MESSAGE);
           return;
       }
        //Buscando Pasajero por DNI
        Pasajero pasaj = pasajeroData.buscarPasajeroPorDni(dni);
        if (pasaj == null) {
            JOptionPane.showMessageDialog(this, "Se puede registrar el Dni.", "Comprobar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se puede ingresar el mismo Dni.", "Error", JOptionPane.WARNING_MESSAGE); 
            limpiar();
        } 
    }//GEN-LAST:event_BuscarbtnActionPerformed

    private void LimpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarbtnActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_LimpiarbtnActionPerformed

    private void RegistrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarbtnActionPerformed
        // TODO add your handling code here:

        String dni = textDNI.getText();
        if (esDNIValido(dni)==false) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI correcto.", "Error", JOptionPane.ERROR_MESSAGE);
            textDNI.setText("");
            return;
        }
        String apellido = txtApellido.getText();
        if (soloLetraApellido(apellido)==false) {
            JOptionPane.showMessageDialog(this, "Ingrese solo letras en el apellido.", "Error", JOptionPane.ERROR_MESSAGE);
            txtApellido.setText("");
            return;
        }
        String nombre = txtNombre.getText();
        if (soloLetraNombre(nombre)==false) {
            JOptionPane.showMessageDialog(this, "Ingrese solo letras en el nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.setText("");
            return;
        }
        String telefono = txtTelefono.getText();
        if (esNumeroValido(telefono)==false) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero correcto.", "Error", JOptionPane.ERROR_MESSAGE);
            txtTelefono.setText("");
            return;
        }
        String correo = txtCorreo.getText();
        if (VerificacionMail(correo)==false) {
            JOptionPane.showMessageDialog(this, "Ingrese un correo valido.", "Error", JOptionPane.ERROR_MESSAGE);
            txtCorreo.setText("");
            return;
        }
        boolean estado = Estado1.isSelected();
        System.out.println(estado);

        if (dni.isBlank() || apellido.isBlank() || nombre.isBlank() || telefono.isBlank() || correo.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
            return;
        }
        
        Pasajero pasa = new Pasajero(nombre,apellido,dni,correo,telefono,estado);
        if (pasajeroData.añadirPasajero(pasa)) {
            JOptionPane.showMessageDialog(this, "Pasajero guardado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el Pasajero.\nQuizás ya haya un Pasajero guardado con ese DNI.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        limpiar();
    }//GEN-LAST:event_RegistrarbtnActionPerformed

    private void SalirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtnActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_SalirbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton Buscarbtn;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel Estado;
    private javax.swing.JCheckBox Estado1;
    private javax.swing.JButton Limpiarbtn;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton Registrarbtn;
    private javax.swing.JButton Salirbtn;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textDNI;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
