package d.Vista;

import b.Entidades.Pasajero;
import c.Data.PasajerosData;
import javax.swing.JOptionPane;

public class FormularioPasajeros extends javax.swing.JInternalFrame {

    PasajerosData pasajeroData;

    public FormularioPasajeros(PasajerosData pasajeroData) {
        initComponents();
        this.pasajeroData = pasajeroData;
    }

    private void limpiar() {
        textDNI.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        Estado1.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DNI = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        textDNI = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        Estado1 = new javax.swing.JCheckBox();
        Limpiarbtn = new javax.swing.JButton();
        Registrarbtn = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Buscarbtn = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FormularioPasajeros");

        DNI.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        DNI.setText("DNI:");

        Apellido.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Apellido.setText("Apellido :");

        Nombre.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Nombre.setText("Nombre :");

        Estado.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Estado.setText("Estado :");

        Limpiarbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Limpiarbtn.setText("Limpiar");
        Limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarbtnActionPerformed(evt);
            }
        });

        Registrarbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Registrarbtn.setText("Registrar");
        Registrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarbtnActionPerformed(evt);
            }
        });

        Salirbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Salirbtn.setText("Salir");
        Salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtnActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Titulo.setText("Pasajero");

        Buscarbtn.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Buscarbtn.setText("Buscar");
        Buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarbtnActionPerformed(evt);
            }
        });

        Telefono.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Telefono.setText("Telefono:");

        Correo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Correo.setText("Correo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(Titulo)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Apellido)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(textDNI)
                        .addGap(8, 8, 8)
                        .addComponent(Buscarbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefono)
                            .addComponent(Correo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Estado)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo)
                            .addComponent(txtTelefono)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Estado1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Limpiarbtn)
                                        .addGap(72, 72, 72)
                                        .addComponent(Registrarbtn)
                                        .addGap(77, 77, 77)
                                        .addComponent(Salirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscarbtn)
                    .addComponent(textDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Estado)
                    .addComponent(Estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limpiarbtn)
                    .addComponent(Registrarbtn)
                    .addComponent(Salirbtn))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarbtnActionPerformed
        // TODO add your handling code here:

        //Validar DNI
        String dni;
        dni = textDNI.getText();

        //Buscando Pasajero por DNI
        Pasajero pasaj = pasajeroData.buscarPasajeroPorDni(dni);
        if (pasaj == null) {
            textDNI.setText("");
            txtApellido.setText("");
            txtNombre.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
            Estado1.setSelected(false);
            JOptionPane.showMessageDialog(null, "Por favor ingrese un DNI");
        } else {
            textDNI.setText(pasaj.getDNI());
            txtApellido.setText(pasaj.getApellido());
            txtNombre.setText(pasaj.getNombre());
            txtTelefono.setText(pasaj.getTelefono());
            txtCorreo.setText(pasaj.getCorreo());
            Estado1.setSelected(pasaj.isEstado());
        }
    }//GEN-LAST:event_BuscarbtnActionPerformed

    private void LimpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarbtnActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_LimpiarbtnActionPerformed

    private void RegistrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarbtnActionPerformed
        // TODO add your handling code here:

        String dni = textDNI.getText();
        String apellido = txtApellido.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        boolean estado = Estado1.isSelected();
        System.out.println(estado);

        if (dni.isBlank() || apellido.isBlank() || nombre.isBlank() || telefono.isBlank() || correo.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
            return;
        }

        Pasajero pasaj = pasajeroData.buscarPasajeroPorDni(dni);

        boolean resultado;
        if (pasaj == null) {
            pasaj = new Pasajero(nombre, apellido, dni, correo, telefono, estado);
            pasajeroData.añadirPasajero(pasaj);
            resultado = true;
        } else {
            pasaj.setDNI(dni);
            pasaj.setNombre(nombre);
            pasaj.setApellido(apellido);
            pasaj.setTelefono(telefono);
            pasaj.setCorreo(correo);
            pasaj.setEstado(estado);
            pasajeroData.modificarPasajero(pasaj);
            resultado = true;
        }

        //imprimir resultado
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Pasajero guardado o modificado");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar al pasajero");
        }

    }//GEN-LAST:event_RegistrarbtnActionPerformed

    private void SalirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtnActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_SalirbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton Buscarbtn;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel Estado;
    private javax.swing.JCheckBox Estado1;
    private javax.swing.JButton Limpiarbtn;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton Registrarbtn;
    private javax.swing.JButton Salirbtn;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField textDNI;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
