/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package d.Vista;

import b.Entidades.Pasaje;
import b.Entidades.Pasajero;
import c.Data.PasajerosData;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author El Notaloko 2.1
 */
public class GestionPasajeros extends javax.swing.JInternalFrame {

     PasajerosData pasajeroData;
    
    /**
     * Creates new form GestionPasajeros
     */
    public GestionPasajeros(PasajerosData pasajeroData) {
        initComponents();
        this.pasajeroData = pasajeroData;
    }

    
    private void limpiar(){  
            txtDNI.setText("");
            txtApellido.setText("");
            txtNombre.setText("");         
            txtTelefono.setText("");
            txtCorreo.setText("");
            Estado1.setSelected(false);
    }
    
    private void setPasajero(boolean iPasaj) {
        txtDNI.setEnabled(iPasaj);
        txtApellido.setEnabled(iPasaj);
        txtNombre.setEnabled(iPasaj);
        txtTelefono.setEnabled(iPasaj);
        txtCorreo.setEditable(iPasaj);
        Estado1.setEnabled(iPasaj);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PasajerosComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        Editarbtn = new javax.swing.JButton();
        Eliminarbtn = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();
        Estado1 = new javax.swing.JCheckBox();
        Limpiarbtn = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("GestionPasajeros");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Titulo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Titulo.setText("Gestion Pasajeros");

        jLabel1.setText("Pasajero:");

        PasajerosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasajerosComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("Correo:");

        jLabel7.setText("Estado:");

        Editarbtn.setText("Editar");
        Editarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarbtnActionPerformed(evt);
            }
        });

        Eliminarbtn.setText("Eliminar");
        Eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarbtnActionPerformed(evt);
            }
        });

        Salirbtn.setText("Salir");
        Salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtnActionPerformed(evt);
            }
        });

        Limpiarbtn.setText("Limpiar");
        Limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasajerosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Limpiarbtn)
                        .addGap(33, 33, 33)
                        .addComponent(Eliminarbtn)
                        .addGap(43, 43, 43)
                        .addComponent(Editarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salirbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Estado1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtApellido)
                    .addComponent(txtNombre)
                    .addComponent(txtTelefono)
                    .addComponent(txtCorreo)
                    .addComponent(txtDNI))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PasajerosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Estado1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Limpiarbtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Editarbtn)
                        .addComponent(Salirbtn)
                        .addComponent(Eliminarbtn)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtnActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_SalirbtnActionPerformed

    private void LimpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarbtnActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_LimpiarbtnActionPerformed

    private void PasajerosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasajerosComboBoxActionPerformed
        // TODO add your handling code here:
        
        setPasajero(true);
        Pasajero pasajeroSeleccionado = (Pasajero) PasajerosComboBox.getSelectedItem();
        if (pasajeroSeleccionado != null) {
            txtDNI.setText(pasajeroSeleccionado.getDNI());
            txtApellido.setText(pasajeroSeleccionado.getApellido());
            txtNombre.setText(pasajeroSeleccionado.getNombre());
            txtTelefono.setText(pasajeroSeleccionado.getTelefono());
            txtCorreo.setText(pasajeroSeleccionado.getCorreo());
            Estado1.setSelected(pasajeroSeleccionado.isEstado());
        } else {
            limpiar();
            Editarbtn.setEnabled(true);
            Editarbtn.setEnabled(true);
            if (PasajerosComboBox.getItemCount() == 0) {
                PasajerosComboBox.setEnabled(false);
            } else {
                PasajerosComboBox.setEnabled(true);
            }
        }
        
    }//GEN-LAST:event_PasajerosComboBoxActionPerformed

    private void EliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarbtnActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        //Validar Pasajero
        String DNI;
        DNI = txtDNI.getText();
        //buscar Pasajero
        Pasajero pasaj = pasajeroData.buscarPasajeroPorDni(DNI);
        if(pasaj==null){
            JOptionPane.showMessageDialog(null, "No se encontro el pasajero vinculado al colectivo");
            return;
        }else{
            if(pasaj.isEstado()==false){
                JOptionPane.showMessageDialog(null, "El pasajero esta dado de baja");
                return;
            }
        }
        // Eliminar pasajeros y limpiar campos (excepto DNI)
        if (pasajeroData.eliminarPasajero(pasaj.getID_Pasajero())){
            txtDNI.setText("");
            txtApellido.setText("");
            txtNombre.setText("");
            txtTelefono.setText("");
            Estado1.setSelected(false);
            JOptionPane.showMessageDialog(this, "Pasajero dado de baja.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Por alguna razon no se pudo eliminar
            JOptionPane.showMessageDialog(this, "No se pudo dar de baja al pasajero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_EliminarbtnActionPerformed

    private void EditarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarbtnActionPerformed
        // TODO add your handling code here:
        
        String DNI = txtDNI.getText();
        String apellido = txtApellido.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        boolean estado = Estado1.isSelected();
        System.out.println(estado);

        Pasajero pasaj = pasajeroData.buscarPasajeroPorDni(DNI);
        boolean resultado;
        if(pasaj != null){
           pasaj.setDNI(DNI);
           pasaj.setApellido(apellido);
           pasaj.setNombre(nombre);
           pasaj.setTelefono(telefono);
           pasaj.setCorreo(correo);
           pasaj.setEstado(estado);
           pasajeroData.modificarPasajero(pasaj);
           resultado=true;
        }else{
           System.out.println("No existe el pasajero");
           resultado=false;
        }
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Pasajero modificado.");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar el pasajero");
        }
        
    }//GEN-LAST:event_EditarbtnActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
        PasajerosComboBox.removeAllItems();
        List<Pasajero> listaPasajero = pasajeroData.listarPasajeros();
        for (Pasajero pasaj : listaPasajero) {
            PasajerosComboBox.addItem(pasaj);
        }
        PasajerosComboBox.setSelectedIndex(-1);
        
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editarbtn;
    private javax.swing.JButton Eliminarbtn;
    private javax.swing.JCheckBox Estado1;
    private javax.swing.JButton Limpiarbtn;
    private javax.swing.JComboBox<Pasajero> PasajerosComboBox;
    private javax.swing.JButton Salirbtn;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
