package d.Vista;

import c.Data.ColectivoData;
import c.Data.HorariosData;
import c.Data.PasajeData;
import c.Data.PasajerosData;
import c.Data.RutaData;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Nahue
 */
public class Inicio_transpuntano extends javax.swing.JFrame {

    JInternalFrame interFrame = null;
    FormularioColectivo formularioColectivo;
    GestionColectivo gestionColectivo;
    GestionPasajero gestionPasajero;
    GestionDeRutas gestionDeRutas;
    GestionHorarios gestionHorarios;
    GestionDeVentas gestionVentas;
    
    ColectivoData colectivoData;
    PasajerosData pasajeroData;
    RutaData rutaData;
    HorariosData horarioData;
    PasajeData pasajeData;
    
    public Inicio_transpuntano() {
        initComponents();
        this.colectivoData = new ColectivoData();
        this.pasajeroData = new PasajerosData();
        this.rutaData = new RutaData();
        this.horarioData = new HorariosData(rutaData);
        this.pasajeData = new PasajeData(pasajeroData,colectivoData,rutaData);
        
        //Gestion Colectivo
        gestionColectivo = new GestionColectivo(colectivoData);
        Escritorio.add(gestionColectivo);
        
        //Formulario Colectivo
        formularioColectivo = new FormularioColectivo(colectivoData);
        Escritorio.add(formularioColectivo);
        
        //Pasajero
        gestionPasajero = new GestionPasajero(pasajeroData);
        Escritorio.add(gestionPasajero);
        
        //Ruta
        gestionDeRutas = new GestionDeRutas(rutaData);
        Escritorio.add(gestionDeRutas);
        
        //Horario
        gestionHorarios = new GestionHorarios(rutaData,horarioData);
        Escritorio.add(gestionHorarios);
        
        //Pasaje
        gestionVentas = new GestionDeVentas(pasajeroData,colectivoData,rutaData,pasajeData);
        Escritorio.add(gestionVentas);
    }
    private void focusIFrame(JInternalFrame iFrame) {

        if (interFrame != null) {
            interFrame.hide();
        }

        interFrame = iFrame;
        interFrame.setVisible(true);
        interFrame.setLocation(100, 100);
        interFrame.moveToFront();
        try {
            interFrame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Inicio_transpuntano.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMformularioColectivo = new javax.swing.JMenuItem();
        jMFormularioColectivo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMGestionPasajero = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMGestionRuta = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMGestionHorario = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMGestionVenta = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Colectivo");

        jMformularioColectivo.setText("Formulario Colectivo");
        jMformularioColectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMformularioColectivoActionPerformed(evt);
            }
        });
        jMenu1.add(jMformularioColectivo);

        jMFormularioColectivo.setText("Gestion Colectivo");
        jMFormularioColectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormularioColectivoActionPerformed(evt);
            }
        });
        jMenu1.add(jMFormularioColectivo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pasajero");

        jMGestionPasajero.setText("GestionPasajero");
        jMGestionPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionPasajeroActionPerformed(evt);
            }
        });
        jMenu2.add(jMGestionPasajero);

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ruta");

        jMGestionRuta.setText("GestionRuta");
        jMGestionRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionRutaActionPerformed(evt);
            }
        });
        jMenu3.add(jMGestionRuta);

        jMenuItem3.setText("jMenuItem3");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Horario");

        jMGestionHorario.setText("GestionHorario");
        jMGestionHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionHorarioActionPerformed(evt);
            }
        });
        jMenu4.add(jMGestionHorario);

        jMenuItem4.setText("jMenuItem4");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Pasaje");

        jMGestionVenta.setText("GestionVenta");
        jMGestionVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionVentaActionPerformed(evt);
            }
        });
        jMenu5.add(jMGestionVenta);

        jMenuItem5.setText("jMenuItem5");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMFormularioColectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormularioColectivoActionPerformed
        // TODO add your handling code here:
        focusIFrame(gestionColectivo);
    }//GEN-LAST:event_jMFormularioColectivoActionPerformed

    private void jMGestionPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionPasajeroActionPerformed
        // TODO add your handling code here:
        focusIFrame(gestionPasajero);
    }//GEN-LAST:event_jMGestionPasajeroActionPerformed

    private void jMGestionRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionRutaActionPerformed
        // TODO add your handling code here:
        focusIFrame(gestionDeRutas);
    }//GEN-LAST:event_jMGestionRutaActionPerformed

    private void jMGestionHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionHorarioActionPerformed
        // TODO add your handling code here:
        focusIFrame(gestionHorarios);
    }//GEN-LAST:event_jMGestionHorarioActionPerformed

    private void jMGestionVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionVentaActionPerformed
        // TODO add your handling code here:
        focusIFrame(gestionVentas);
    }//GEN-LAST:event_jMGestionVentaActionPerformed

    private void jMformularioColectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMformularioColectivoActionPerformed
        // TODO add your handling code here:
        focusIFrame(formularioColectivo);
    }//GEN-LAST:event_jMformularioColectivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_transpuntano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_transpuntano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_transpuntano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_transpuntano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_transpuntano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem jMFormularioColectivo;
    private javax.swing.JMenuItem jMGestionHorario;
    private javax.swing.JMenuItem jMGestionPasajero;
    private javax.swing.JMenuItem jMGestionRuta;
    private javax.swing.JMenuItem jMGestionVenta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMformularioColectivo;
    // End of variables declaration//GEN-END:variables
}
